"""empty message

Revision ID: 08ed86115af6
Revises: 6460b1fb3889
Create Date: 2024-05-11 00:47:55.842911

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '08ed86115af6'
down_revision: Union[str, None] = '6460b1fb3889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', "_name", nullable=False, new_column_name="name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', "name", nullable=True, new_column_name="_name")
    # ### end Alembic commands ###
